schema_version: 1

context:
  version: "0.0.8"
  python_min: "3.10"

package:
  name: interpax-fft
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/i/interpax-fft/interpax_fft-${{ version }}.tar.gz
  sha256: b5bf70e12ce95af808bdcdba2d727dc7eea3a67c30eb888ef70762b52b259c0d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=42
    - versioneer-518
    - pip
  run:
    - python >=${{ python_min }}
    - equinox >=0.11.0,!=0.13.3
    - jax >=0.5.0,!=0.5.1,!=0.5.2,!=0.6.0,!=0.7.1,!=0.8.2,!=0.9.0
    - jaxtyping >=0.2.24
    - numpy >=1.20.0
    # FIXME upstream: Required for version import
    - packaging
    # FIXME upstream: visualization required for import
    - matplotlib-base

tests:
  - python:
      imports:
        - interpax_fft
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Fourier interpolation and function approximation with JAX
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/unalmis/interpax_fft
  repository: https://github.com/unalmis/interpax_fft
  documentation: https://unalmis.github.io/interpax_fft/

extra:
  recipe-maintainers:
    - matthewfeickert
